### PR TITLE
[mobile-client-overview] change bindable services counter logic

### PR DESCRIPTION
**Pull request by witmicko**
https://issues.jboss.org/browse/AEROGEAR-3297

image

## Verification steps
1. create a new project
2. provision Mobile CI/CD service
3. Provision Android Client
4. Create a build for the client
5. Mobile Overview should show build information
6. Mobile overview should have an accurate bindable service counter
7. Provision bindable service, the counter should update

### CODE REVIEW

**Comment by maleck13** [comment]
👀

**Review by maleck13 — APPROVED** [review]
code looks ok to me will let @sedroche and @JameelB have the final say. Testing locally now

**Comment by maleck13** [comment]
@witmicko may need a rebase

**Comment by maleck13** [comment]
Verified works as expected. Just one question I have. I created a build but I only saw it once I started the build. Do we want them to show up even if no build has actually been done?

**Comment by witmicko** [comment]
@maleck13 I think it is consistent with the premise of overview being strictly informative, nothing to show unless actual build has started and we are interested in its status

**Comment by maleck13** [comment]
Ok then I happy it works as expected

**Comment by sedroche** [comment]
LGTM @witmicko Can you change the tag to [mobile-client-overview] though please?

**Review by sedroche — APPROVED** [review]

**Pull request merged**
